<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>parrot</string>
	</array>
	<key>name</key>
	<string>Parrot</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.parrot</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.parrot</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.parrot</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#{</string>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>string-interpolation</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.parrot</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\+</string>
							<key>name</key>
							<string>keyword.operator.parrot</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(do|end|extends|with|as|in|or|is|var|and|not|proc|enum|null|file|lazy|super|object|const|event|_func|_args|struct|repeat|pub|static|extern|default|priv|internal|undefined)\b</string>
			<key>name</key>
			<string>keyword.reserved.parrot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|return|else|case|break|for|while|switch|continue)\b</string>
			<key>name</key>
			<string>keyword.control.flow-control.parrot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>string.boolean.parrot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#\w+</string>
			<key>name</key>
			<string>meta.preprocessor.parrot</string>
		</dict>
				<dict>
			<key>match</key>
			<string>\b[A-Z_]+\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.parrot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(-|\.)?\b[0-9]+(\.[0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.parrot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\w|[\+|-|\*|/|%|=|!|\^|~|\||\?|&lt;|&gt;|&amp;])+(?=\s*\()</string>
			<key>name</key>
			<string>support.function.parrot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|\*|/|%|=|!|\^|~|\||\?|&lt;|&gt;|&amp;</string>
			<key>name</key>
			<string>keyword.operator.parrot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w+(?=\s*:)</string>
			<key>name</key>
			<string>variable.other.parrot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\.)\w+(?=\.|\s|,|;|\)|\?|\+|\-|=)</string>
			<key>name</key>
			<string>support.constant.parrot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([A-Z])\w+\b</string>
			<key>name</key>
			<string>entity.name.type.class.parrot</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w</string>
			<key>name</key>
			<string>variable.other.parrot</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.parrot</string>
	<key>uuid</key>
	<string>6A273AF0-EB4A-11E3-AC10-0800200C9A66</string>
</dict>
</plist>