<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>density</string>
	</array>
	<key>name</key>
	<string>Density</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.density</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.density</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.density</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\\\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>string-interpolation</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.density</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\+</string>
							<key>name</key>
							<string>keyword.operator.density</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(with|as|in|or|is|var|and|not|func|enum|null|file|lazy|super|class|const|event|_func|_args|struct|repeat|public|static|extern|import|module|default|private|internal|undefined)\b</string>
			<key>name</key>
			<string>keyword.reserved.density</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|return|else|case|break|for|while|switch|continue)\b</string>
			<key>name</key>
			<string>keyword.control.flow-control.density</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>string.boolean.density</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#\w+</string>
			<key>name</key>
			<string>meta.preprocessor.density</string>
		</dict>
				<dict>
			<key>match</key>
			<string>\b[A-Z_]+\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.density</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(-|\.)?\b[0-9]+(\.[0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.density</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\w|[\+|-|\*|/|%|=|!|\^|~|\||\?|&lt;|&gt;|&amp;])+(?=\s*\()</string>
			<key>name</key>
			<string>support.function.density</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|\*|/|%|=|!|\^|~|\||\?|&lt;|&gt;|&amp;</string>
			<key>name</key>
			<string>keyword.operator.density</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w+(?=\s*:)</string>
			<key>name</key>
			<string>variable.other.density</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\.)\w+(?=\.|\s|,|;|\)|\?|\+|\-|=)</string>
			<key>name</key>
			<string>support.constant.density</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([A-Z])\w+\b</string>
			<key>name</key>
			<string>entity.name.type.class.density</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w</string>
			<key>name</key>
			<string>variable.other.density</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.density</string>
	<key>uuid</key>
	<string>6A273AF0-EB4A-11E3-AC10-0800200C9A66</string>
</dict>
</plist>